# Your Name or Company
title: Carlos Daniel Carrasco

# Description of your website. This is used for social sharing.
description: Computational Cognitive Neuroscientist
# A brief blurb about yourself
content: I am currently a PhD Candidate in the Neuroscience program at UC Davis working with Dr. Erie Boorman and Dr. Steven Luck. My interests lie at the intersection of memory and decision making processes that guide behavior. Currently I am working on projects involving working memory, the temporal credit assignment problem, and memory reinstatement decoding using EEG. Outside of lab I enjoy going out with friends, playing the guitar, sight seeing, and spending time with loved ones.
# Add your social links
social:
  - platform: Github
    url: https://github.com/mojorisin24
  - platform: Google Scholar
    url: https://scholar.google.com/citations?user=Nh0i3UQAAAAJ&hl=en
  - platform: Twitter
    url: https://twitter.com/CDCarrasco_
  - platform: Academic Profile
    url: https://grad.neuroscience.ucdavis.edu/student-profile?id=10908

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: #"UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
