# Your Name or Company
title: Carlos Daniel Carrasco

# Description of your website. This is used for social sharing.
description: Computational Cognitive Neuroscientist
# A brief blurb about yourself
content: I am currently a PhD Candidate in the Neuroscience program at UC Davis working with Dr. Erie Boorman and Dr. Steven Luck. My interests lie at the intersection of memory and decision making processes that guide behavior. Currently I am working on projects involving working memory, the temporal credit assignment problem, and soon memory reinstatement decoding using EEG. Outside of lab I enjoy going out with friends, playing the guitar, and occasionally playing videogames or trying out new hobbies
# Add your social links
social:
  - platform: github
    url: https://github.com/mojorisin24
  - platform: Luck Lab
    url: https://lucklab.ucdavis.edu/
  - platform: LDM Lab
    url: http://ldm.ucdavis.edu/
  - platform: Twitter
    url: https://twitter.com/CDCarrasco_

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: #"UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
