# Your Name or Company
title: Carlos Daniel Carrasco

# Description of your website. This is used for social sharing.
description: Neuroscience PhD Candidate at UC Davis 
# A brief blurb about yourself
content: Hello Everyone. I am interested in memory processes and how they impact decisions. 

# Add your social links
social:
  - platform: github
    url: https://github.com/mojorisin24
  - platform: Luck Lab
    url: https://lucklab.ucdavis.edu/
  - platform: LDM Lab
    url: http://ldm.ucdavis.edu/
  - platform: Twitter
    url: https://twitter.com/CDCarrasco_

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: #"UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
